/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description 登录。两种失败返回**同一句话**，且**耗时相当**。
         *
         *     错误信息合并是常识；耗时对齐同样必要——`user is None` 直接短路的话，
         *     "账号不存在"会比"口令错误"快一个数量级（实测 3.3ms vs 38ms，PBKDF2
         *     20 万轮的差距），等于把账号枚举从错误信息挪到了计时上。而演示口令
         *     就印在登录页上，枚举出账号就能直接撞库。
         *
         *     所以账号不存在时也跑一次校验，只是拿一个永远对不上的哈希。
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description 建号。只有管理员令牌能调。
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Users
         * @description 账号列表（管理员）。用于用户管理页，只返回公开字段。
         *
         *     GET 带不了请求体，所以令牌走查询参数（`token_from_query` 会验签）。
         */
        get: operations["users_api_auth_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasources */
        get: operations["list_datasources_api_datasources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasources/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Demo
         * @description 一键载入演示数据（建 5 表 + 灌虚构数据 + 初始化平台元数据库）。
         *
         *     **必须管理员**：它会**先删掉再重建**业务库（`build_database` 里有
         *     `os.remove`），所有既有数据没了。管理员在页面上点一下没问题，
         *     但匿名或局域网里的任何人都能触发就不是"演示便利"而是数据销毁了。
         */
        post: operations["create_demo_api_datasources_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasources/{datasource_id}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schema */
        get: operations["get_schema_api_datasources__datasource_id__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Policies
         * @description 所有已定案策略的 id 列表（供数据源页展示）。
         */
        get: operations["list_policies_api_policies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/{datasource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Policy */
        get: operations["get_policy_api_policies__datasource_id__get"];
        /**
         * Update Policy
         * @description 更新策略。只改 YAML 中明确提交的键，其余保留。
         *
         *     **必须管理员**：这个接口决定了医盾拦什么——把 `id_card` 从 blocked 改成
         *     free，整条防线就没了。它曾经完全敞开：匿名 PUT 就能改写磁盘上的策略文件，
         *     实测返回 200 且文件真的被改。查接口敞开只是"多开一个终端"，这个接口敞开
         *     是**把安全引擎本身交出去**。
         */
        put: operations["update_policy_api_policies__datasource_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/{datasource_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validate Policy
         * @description 校验策略可被算法层正确加载（健康检查/接入新数据源时用）。
         */
        get: operations["validate_policy_api_policies__datasource_id__validate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Query */
        post: operations["run_query_api_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query/direct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Direct Query
         * @description 自由提问：**缓存优先，未命中调模型翻译**。
         *
         *     缓存的是**计划**不是答案——命中后照样走层一准入与层二审计，安全演示
         *     一点不打折。缓存的价值不只是提速（模型翻译约 47 秒），更是保演示质量：
         *     模型倾向选更安全的写法，审计出来的违规常为 0；打磨过的计划才会触发
         *     Rule C 拆分与跨域 JOIN 事件。
         */
        post: operations["run_direct_query_api_query_direct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/detection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detection Metrics */
        get: operations["detection_metrics_api_metrics_detection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reports
         * @description 列出**该令牌发起的**查询报告。
         *
         *     这个端点原先不收任何身份、无过滤地返回全表，于是医生跑完查询、患者
         *     登录后看到的是医生的记录。现在身份既必填、又必须签名有效。
         */
        get: operations["reports_api_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Detail */
        get: operations["report_detail_api_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Report */
        get: operations["export_report_api_reports__report_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/smart-doctor/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_smart_doctor_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 健康检查：算法层可用性 + 各路由挂载状态。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdmissionInfo */
        AdmissionInfo: {
            /** Passed */
            passed: boolean;
            /** Reason */
            reason?: string | null;
            /** Checked Tables */
            checked_tables: string[];
            /**
             * Bound To Subject
             * @default false
             */
            bound_to_subject: boolean;
        };
        /**
         * CrossDomainRule
         * @description 跨域关联规则。
         *
         *     字段给默认值是刻意的：策略 YAML 由人手工维护，缺字段时应能在界面上
         *     显示为一条"不完整规则"，而不是让整个策略页 500。结构合法性由算法层
         *     `load_ssa` 把关（`/api/policies/{id}/validate` 暴露其结果）。
         */
        CrossDomainRule: {
            /** Table Pair */
            table_pair?: string[];
            /**
             * Join Key
             * @default
             */
            join_key: string;
            /**
             * Forbid Personal Level
             * @default false
             */
            forbid_personal_level: boolean;
            /**
             * Allow Aggregate Level
             * @default false
             */
            allow_aggregate_level: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** DatasourceInfo */
        DatasourceInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Table Count */
            table_count: number;
            /** Column Count */
            column_count: number;
            /** Policy Ready */
            policy_ready: boolean;
        };
        /** DatasourceSchema */
        DatasourceSchema: {
            /** Tables */
            tables: components["schemas"]["SchemaTable"][];
        };
        /** DegradationInfo */
        DegradationInfo: {
            /**
             * Level
             * @enum {string}
             */
            level: "L0" | "L1" | "L2" | "L3";
            /** Label */
            label: string;
            /** Message */
            message: string;
            /**
             * Message Cn
             * @default
             */
            message_cn: string;
        };
        /** DemoDatasourceResult */
        DemoDatasourceResult: {
            /** Id */
            id: string;
            /** Created */
            created: boolean;
        };
        /**
         * DemoLoadRequest
         * @description 一键载入演示数据。**只有管理员能调**——它会删掉并重建业务库。
         */
        DemoLoadRequest: {
            token: components["schemas"]["Token"];
        };
        /**
         * DetectionMetrics
         * @description 检测效能——数字来自论文仓库 results/rq3/ 实测，不得杜撰。
         */
        DetectionMetrics: {
            precision: components["schemas"]["MetricValue"];
            recall: components["schemas"]["MetricValue"];
            blocked_detection: components["schemas"]["MetricValue"];
            /** Source */
            source: string;
        };
        /**
         * DirectQueryRequest
         * @description 自然语言直查。
         */
        DirectQueryRequest: {
            token: components["schemas"]["Token"];
            /** Datasource Id */
            datasource_id: string;
            /** Question */
            question: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthInfo */
        HealthInfo: {
            /** Status */
            status: string;
            /** Algo Engine */
            algo_engine: string;
            /** Policies */
            policies: string[];
            /** Routes */
            routes: string[];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Account */
            account: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            user: components["schemas"]["UserInfo"];
            token: components["schemas"]["Token"];
        };
        /** MetricValue */
        MetricValue: {
            /** Value */
            value: number;
            /** Detail */
            detail: string;
        };
        /**
         * MetricsInfo
         * @description 审计阶段的开销——**不是查询执行的开销**。
         *
         *     `llm_calls` / `db_access` 恒为 0，这是「零 LLM、零查库」安全声明的
         *     可验证形式：审计器不调模型（无提示注入面）、不碰数据库（无困惑代理面）。
         *     查询本身的执行不计入本指标——`result` 非空即表示执行过。
         */
        MetricsInfo: {
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Llm Calls */
            llm_calls: number;
            /** Db Access */
            db_access: number;
        };
        /** PlanItem */
        PlanItem: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            /** Sql Before */
            sql_before: string;
            /** Sql After */
            sql_after: string;
            /** Is Final */
            is_final: boolean;
        };
        /** Policy */
        Policy: {
            /** Datasource Id */
            datasource_id: string;
            /** Column Labels */
            column_labels: {
                [key: string]: {
                    [key: string]: "free" | "controlled" | "blocked";
                };
            };
            /** Column Reasons */
            column_reasons: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /** Cross Domain Rules */
            cross_domain_rules: components["schemas"]["CrossDomainRule"][];
            /** Review Status */
            review_status: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /** Table Aliases */
            table_aliases: {
                [key: string]: string;
            };
            /** Column Aliases */
            column_aliases: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        /** PolicyList */
        PolicyList: {
            /** Datasource Ids */
            datasource_ids: string[];
        };
        /**
         * PolicyUpdateRequest
         * @description 更新安全策略。**只有管理员能改**——这两个接口决定了医盾拦什么。
         */
        PolicyUpdateRequest: {
            token: components["schemas"]["Token"];
            /** Column Labels */
            column_labels?: {
                [key: string]: {
                    [key: string]: string;
                };
            } | null;
            /** Cross Domain Rules */
            cross_domain_rules?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** PolicyUpdateResult */
        PolicyUpdateResult: {
            /** Saved */
            saved: boolean;
            /** Datasource Id */
            datasource_id: string;
        };
        /**
         * PolicyValidation
         * @description 策略可加载性校验。
         *
         *     成功与失败两种形状：成功时带 tables/columns/cross_domain_rules 计数，
         *     失败时带 error 文案，故后四者均可为空。
         */
        PolicyValidation: {
            /** Ok */
            ok: boolean;
            /** Datasource Id */
            datasource_id: string;
            /** Tables */
            tables?: number | null;
            /** Columns */
            columns?: number | null;
            /** Cross Domain Rules */
            cross_domain_rules?: number | null;
            /** Error */
            error?: string | null;
        };
        /** QueryRequest */
        QueryRequest: {
            token: components["schemas"]["Token"];
            /** Datasource Id */
            datasource_id: string;
            /** Question Id */
            question_id: string;
        };
        /** QueryResponse */
        QueryResponse: {
            admission: components["schemas"]["AdmissionInfo"];
            /** Question */
            question: string;
            /** Plan */
            plan: components["schemas"]["PlanItem"][];
            /** Events */
            events: components["schemas"]["SecurityEvent"][];
            rewrite: components["schemas"]["RewriteInfo"];
            degradation: components["schemas"]["DegradationInfo"];
            metrics: components["schemas"]["MetricsInfo"];
            result?: components["schemas"]["ResultSet"] | null;
        };
        /**
         * RegisterRequest
         * @description 建号。**只有管理员令牌能调**（医院里开号是信息科的活）。
         */
        RegisterRequest: {
            token: components["schemas"]["Token"];
            /** Account */
            account: string;
            /** Password */
            password: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "staff" | "patient";
            /** Subject Id */
            subject_id?: string | null;
            /**
             * Display Name
             * @default
             */
            display_name: string;
        };
        /**
         * ReportDetail
         * @description 报告详情 = 摘要字段 + 完整 QueryResponse 快照。
         *
         *     `payload` 声明为 `QueryResponse` 而不是 `Dict[str, Any]`：它本来就是
         *     那次查询的完整响应（存库时就是 `resp.model_dump()`）。写成泛型字典会让
         *     安全报告页在 TS 里整页退化成 unknown——而那正是承载审计证据的核心页面。
         */
        ReportDetail: {
            /** Id */
            id: number;
            /** Question */
            question: string;
            /**
             * Token Type
             * @enum {string}
             */
            token_type: "staff" | "patient";
            /** Created At */
            created_at: string;
            /**
             * Degradation Level
             * @enum {string}
             */
            degradation_level: "L0" | "L1" | "L2" | "L3";
            /** Event Count */
            event_count: number;
            payload: components["schemas"]["QueryResponse"];
        };
        /** ReportSummary */
        ReportSummary: {
            /** Id */
            id: number;
            /** Question */
            question: string;
            /**
             * Token Type
             * @enum {string}
             */
            token_type: "staff" | "patient";
            /** Created At */
            created_at: string;
            /**
             * Degradation Level
             * @enum {string}
             */
            degradation_level: "L0" | "L1" | "L2" | "L3";
            /** Event Count */
            event_count: number;
        };
        /** ResultSet */
        ResultSet: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: unknown[][];
        };
        /** RewriteInfo */
        RewriteInfo: {
            /** Applied */
            applied: number;
            /** Log */
            log: string[];
        };
        /** SchemaColumn */
        SchemaColumn: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Pk
             * @default false
             */
            pk: boolean;
        };
        /** SchemaTable */
        SchemaTable: {
            /** Name */
            name: string;
            /** Columns */
            columns: components["schemas"]["SchemaColumn"][];
        };
        /** SecurityEvent */
        SecurityEvent: {
            /** Sub Query Id */
            sub_query_id: string;
            /** Type */
            type: string;
            /** Type Label */
            type_label: string;
            /** Column */
            column: string;
            /** Severity */
            severity: string;
            /** Severity Label */
            severity_label: string;
            /** Detail */
            detail: string;
        };
        /**
         * SmartDoctorAdvice
         * @description 下一步建议（来源：医院审核知识库）。
         */
        SmartDoctorAdvice: {
            /** Source */
            source: string;
            /**
             * Text
             * @default
             */
            text: string;
            /** Actions */
            actions?: string[];
            /**
             * Urgent
             * @default false
             */
            urgent: boolean;
        };
        /**
         * SmartDoctorDataBlock
         * @description 院内数据（来源：医院主库）。经医盾层一准入 + 层二审计后返回。
         */
        SmartDoctorDataBlock: {
            /** Source */
            source: string;
            /** Columns */
            columns?: string[];
            /** Rows */
            rows?: unknown[][];
            /**
             * Sql After
             * @default
             */
            sql_after: string;
            /**
             * Degradation Level
             * @default L0
             */
            degradation_level: string;
        };
        /**
         * SmartDoctorInterpretation
         * @description 通俗解读（来源：医院审核知识库）。
         *
         *     items 为逐条说明（如每个检验项/每种药对应一条），字段随意图不同，
         *     故用宽松字典——测试会逐键断言，前端按意图渲染。
         */
        SmartDoctorInterpretation: {
            /** Source */
            source: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Text
             * @default
             */
            text: string;
            /** Items */
            items?: {
                [key: string]: unknown;
            }[];
        };
        /** SmartDoctorRequest */
        SmartDoctorRequest: {
            token: components["schemas"]["Token"];
            /** Datasource Id */
            datasource_id: string;
            /** Question */
            question: string;
        };
        /** SmartDoctorResponse */
        SmartDoctorResponse: {
            /**
             * Intent
             * @enum {string}
             */
            intent: "lab" | "medication" | "symptom" | "disease" | "fallback";
            /** Question */
            question: string;
            admission: components["schemas"]["AdmissionInfo"];
            degradation: components["schemas"]["DegradationInfo"];
            data?: components["schemas"]["SmartDoctorDataBlock"] | null;
            interpretation?: components["schemas"]["SmartDoctorInterpretation"] | null;
            advice?: components["schemas"]["SmartDoctorAdvice"] | null;
        };
        /**
         * Token
         * @description 数据访问凭证。
         *
         *     `exp` / `sig` 由 `POST /api/auth/login` 签发，覆盖 type/subject_id/exp
         *     三者。**每个收令牌的端点都会验签**——在此之前令牌是客户端自己拼的，
         *     手搓一个 `{"type":"patient","subject_id":"P002"}` 就能读别人的安全报告。
         */
        Token: {
            /**
             * Type
             * @enum {string}
             */
            type: "staff" | "patient";
            /** Subject Id */
            subject_id?: string | null;
            /** Account */
            account?: string | null;
            /** Exp */
            exp?: number | null;
            /** Sig */
            sig?: string | null;
        };
        /**
         * UserInfo
         * @description 账号的公开信息——**不含口令哈希**。
         */
        UserInfo: {
            /** Account */
            account: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "staff" | "patient";
            /** Subject Id */
            subject_id?: string | null;
            /**
             * Display Name
             * @default
             */
            display_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    users_api_auth_users_get: {
        parameters: {
            query: {
                token_type: "staff" | "patient";
                subject_id?: string | null;
                account?: string | null;
                exp?: number | null;
                sig?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasources_api_datasources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasourceInfo"][];
                };
            };
        };
    };
    create_demo_api_datasources_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoLoadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoDatasourceResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_api_datasources__datasource_id__schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasourceSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_policies_api_policies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyList"];
                };
            };
        };
    };
    get_policy_api_policies__datasource_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_policy_api_policies__datasource_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasource_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyUpdateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_policy_api_policies__datasource_id__validate_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyValidation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_query_api_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_direct_query_api_query_direct_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detection_metrics_api_metrics_detection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionMetrics"];
                };
            };
        };
    };
    reports_api_reports_get: {
        parameters: {
            query: {
                limit?: number;
                token_type: "staff" | "patient";
                subject_id?: string | null;
                account?: string | null;
                exp?: number | null;
                sig?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_detail_api_reports__report_id__get: {
        parameters: {
            query: {
                token_type: "staff" | "patient";
                subject_id?: string | null;
                account?: string | null;
                exp?: number | null;
                sig?: string | null;
            };
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_report_api_reports__report_id__export_get: {
        parameters: {
            query: {
                token_type: "staff" | "patient";
                subject_id?: string | null;
                account?: string | null;
                exp?: number | null;
                sig?: string | null;
            };
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_smart_doctor_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmartDoctorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmartDoctorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthInfo"];
                };
            };
        };
    };
}
