/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/datasources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasources */
        get: operations["list_datasources_api_datasources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasources/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Demo
         * @description 一键载入演示数据（建 5 表 + 灌虚构数据 + 初始化平台元数据库）。
         */
        post: operations["create_demo_api_datasources_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasources/{datasource_id}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schema */
        get: operations["get_schema_api_datasources__datasource_id__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Policies
         * @description 所有已定案策略的 id 列表（供数据源页展示）。
         */
        get: operations["list_policies_api_policies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/{datasource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Policy */
        get: operations["get_policy_api_policies__datasource_id__get"];
        /**
         * Update Policy
         * @description 更新策略。只改 YAML 中明确提交的键，其余保留。
         */
        put: operations["update_policy_api_policies__datasource_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/{datasource_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validate Policy
         * @description 校验策略可被算法层正确加载（健康检查/接入新数据源时用）。
         */
        get: operations["validate_policy_api_policies__datasource_id__validate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Query */
        post: operations["run_query_api_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query/direct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Direct Query
         * @description 自由提问：**缓存优先，未命中调模型翻译**。
         *
         *     缓存的是**计划**不是答案——命中后照样走层一准入与层二审计，安全演示
         *     一点不打折。缓存的价值不只是提速（模型翻译约 47 秒），更是保演示质量：
         *     模型倾向选更安全的写法，审计出来的违规常为 0；打磨过的计划才会触发
         *     Rule C 拆分与跨域 JOIN 事件。
         */
        post: operations["run_direct_query_api_query_direct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/detection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detection Metrics */
        get: operations["detection_metrics_api_metrics_detection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reports */
        get: operations["reports_api_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Detail */
        get: operations["report_detail_api_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Report */
        get: operations["export_report_api_reports__report_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 健康检查：算法层可用性 + 各路由挂载状态。
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdmissionInfo */
        AdmissionInfo: {
            /** Passed */
            passed: boolean;
            /** Reason */
            reason?: string | null;
            /** Checked Tables */
            checked_tables: string[];
            /**
             * Bound To Subject
             * @default false
             */
            bound_to_subject: boolean;
        };
        /**
         * CrossDomainRule
         * @description 跨域关联规则。
         *
         *     字段给默认值是刻意的：策略 YAML 由人手工维护，缺字段时应能在界面上
         *     显示为一条"不完整规则"，而不是让整个策略页 500。结构合法性由算法层
         *     `load_ssa` 把关（`/api/policies/{id}/validate` 暴露其结果）。
         */
        CrossDomainRule: {
            /** Table Pair */
            table_pair?: string[];
            /**
             * Join Key
             * @default
             */
            join_key: string;
            /**
             * Forbid Personal Level
             * @default false
             */
            forbid_personal_level: boolean;
            /**
             * Allow Aggregate Level
             * @default false
             */
            allow_aggregate_level: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** DatasourceInfo */
        DatasourceInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Table Count */
            table_count: number;
            /** Column Count */
            column_count: number;
            /** Policy Ready */
            policy_ready: boolean;
        };
        /** DatasourceSchema */
        DatasourceSchema: {
            /** Tables */
            tables: components["schemas"]["SchemaTable"][];
        };
        /** DegradationInfo */
        DegradationInfo: {
            /**
             * Level
             * @enum {string}
             */
            level: "L0" | "L1" | "L2" | "L3";
            /** Label */
            label: string;
            /** Message */
            message: string;
            /**
             * Message Cn
             * @default
             */
            message_cn: string;
        };
        /** DemoDatasourceResult */
        DemoDatasourceResult: {
            /** Id */
            id: string;
            /** Created */
            created: boolean;
        };
        /**
         * DetectionMetrics
         * @description 检测效能——数字来自论文仓库 results/rq3/ 实测，不得杜撰。
         */
        DetectionMetrics: {
            precision: components["schemas"]["MetricValue"];
            recall: components["schemas"]["MetricValue"];
            blocked_detection: components["schemas"]["MetricValue"];
            /** Source */
            source: string;
        };
        /**
         * DirectQueryRequest
         * @description 自然语言直查。
         */
        DirectQueryRequest: {
            token: components["schemas"]["Token"];
            /** Datasource Id */
            datasource_id: string;
            /** Question */
            question: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthInfo */
        HealthInfo: {
            /** Status */
            status: string;
            /** Algo Engine */
            algo_engine: string;
            /** Policies */
            policies: string[];
            /** Routes */
            routes: string[];
        };
        /** MetricValue */
        MetricValue: {
            /** Value */
            value: number;
            /** Detail */
            detail: string;
        };
        /**
         * MetricsInfo
         * @description 审计阶段的开销——**不是查询执行的开销**。
         *
         *     `llm_calls` / `db_access` 恒为 0，这是「零 LLM、零查库」安全声明的
         *     可验证形式：审计器不调模型（无提示注入面）、不碰数据库（无困惑代理面）。
         *     查询本身的执行不计入本指标——`result` 非空即表示执行过。
         */
        MetricsInfo: {
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Llm Calls */
            llm_calls: number;
            /** Db Access */
            db_access: number;
        };
        /** PlanItem */
        PlanItem: {
            /** Id */
            id: number;
            /** Description */
            description: string;
            /** Sql Before */
            sql_before: string;
            /** Sql After */
            sql_after: string;
            /** Is Final */
            is_final: boolean;
        };
        /** Policy */
        Policy: {
            /** Datasource Id */
            datasource_id: string;
            /** Column Labels */
            column_labels: {
                [key: string]: {
                    [key: string]: "free" | "controlled" | "blocked";
                };
            };
            /** Column Reasons */
            column_reasons: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /** Cross Domain Rules */
            cross_domain_rules: components["schemas"]["CrossDomainRule"][];
            /** Review Status */
            review_status: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /** Table Aliases */
            table_aliases: {
                [key: string]: string;
            };
            /** Column Aliases */
            column_aliases: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        /** PolicyList */
        PolicyList: {
            /** Datasource Ids */
            datasource_ids: string[];
        };
        /** PolicyUpdate */
        PolicyUpdate: {
            /** Column Labels */
            column_labels?: {
                [key: string]: {
                    [key: string]: string;
                };
            } | null;
            /** Cross Domain Rules */
            cross_domain_rules?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** PolicyUpdateResult */
        PolicyUpdateResult: {
            /** Saved */
            saved: boolean;
            /** Datasource Id */
            datasource_id: string;
        };
        /**
         * PolicyValidation
         * @description 策略可加载性校验。
         *
         *     成功与失败两种形状：成功时带 tables/columns/cross_domain_rules 计数，
         *     失败时带 error 文案，故后四者均可为空。
         */
        PolicyValidation: {
            /** Ok */
            ok: boolean;
            /** Datasource Id */
            datasource_id: string;
            /** Tables */
            tables?: number | null;
            /** Columns */
            columns?: number | null;
            /** Cross Domain Rules */
            cross_domain_rules?: number | null;
            /** Error */
            error?: string | null;
        };
        /** QueryRequest */
        QueryRequest: {
            token: components["schemas"]["Token"];
            /** Datasource Id */
            datasource_id: string;
            /** Question Id */
            question_id: string;
        };
        /** QueryResponse */
        QueryResponse: {
            admission: components["schemas"]["AdmissionInfo"];
            /** Question */
            question: string;
            /** Plan */
            plan: components["schemas"]["PlanItem"][];
            /** Events */
            events: components["schemas"]["SecurityEvent"][];
            rewrite: components["schemas"]["RewriteInfo"];
            degradation: components["schemas"]["DegradationInfo"];
            metrics: components["schemas"]["MetricsInfo"];
            result?: components["schemas"]["ResultSet"] | null;
        };
        /**
         * ReportDetail
         * @description 报告详情 = 摘要字段 + 完整 QueryResponse 快照。
         *
         *     `payload` 声明为 `QueryResponse` 而不是 `Dict[str, Any]`：它本来就是
         *     那次查询的完整响应（存库时就是 `resp.model_dump()`）。写成泛型字典会让
         *     安全报告页在 TS 里整页退化成 unknown——而那正是承载审计证据的核心页面。
         */
        ReportDetail: {
            /** Id */
            id: number;
            /** Question */
            question: string;
            /**
             * Token Type
             * @enum {string}
             */
            token_type: "staff" | "patient";
            /** Created At */
            created_at: string;
            /**
             * Degradation Level
             * @enum {string}
             */
            degradation_level: "L0" | "L1" | "L2" | "L3";
            /** Event Count */
            event_count: number;
            payload: components["schemas"]["QueryResponse"];
        };
        /** ReportSummary */
        ReportSummary: {
            /** Id */
            id: number;
            /** Question */
            question: string;
            /**
             * Token Type
             * @enum {string}
             */
            token_type: "staff" | "patient";
            /** Created At */
            created_at: string;
            /**
             * Degradation Level
             * @enum {string}
             */
            degradation_level: "L0" | "L1" | "L2" | "L3";
            /** Event Count */
            event_count: number;
        };
        /** ResultSet */
        ResultSet: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: unknown[][];
        };
        /** RewriteInfo */
        RewriteInfo: {
            /** Applied */
            applied: number;
            /** Log */
            log: string[];
        };
        /** SchemaColumn */
        SchemaColumn: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Pk
             * @default false
             */
            pk: boolean;
        };
        /** SchemaTable */
        SchemaTable: {
            /** Name */
            name: string;
            /** Columns */
            columns: components["schemas"]["SchemaColumn"][];
        };
        /** SecurityEvent */
        SecurityEvent: {
            /** Sub Query Id */
            sub_query_id: string;
            /** Type */
            type: string;
            /** Type Label */
            type_label: string;
            /** Column */
            column: string;
            /** Severity */
            severity: string;
            /** Severity Label */
            severity_label: string;
            /** Detail */
            detail: string;
        };
        /** Token */
        Token: {
            /**
             * Type
             * @enum {string}
             */
            type: "staff" | "patient";
            /** Subject Id */
            subject_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_datasources_api_datasources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasourceInfo"][];
                };
            };
        };
    };
    create_demo_api_datasources_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoDatasourceResult"];
                };
            };
        };
    };
    get_schema_api_datasources__datasource_id__schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasourceSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_policies_api_policies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyList"];
                };
            };
        };
    };
    get_policy_api_policies__datasource_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_policy_api_policies__datasource_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasource_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyUpdateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_policy_api_policies__datasource_id__validate_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyValidation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_query_api_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_direct_query_api_query_direct_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detection_metrics_api_metrics_detection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionMetrics"];
                };
            };
        };
    };
    reports_api_reports_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_detail_api_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_report_api_reports__report_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthInfo"];
                };
            };
        };
    };
}
